"""Render the final postmortem.md report."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from jinja2 import Template

from postmortem_pilot import __version__

TEMPLATE = """\
# 🚨 Postmortem Report

> Generated by [postmortem-pilot](https://github.com/eya-lachhab/postmortem-pilot) on {{ timestamp }}

---

## 📋 Deploy Summary

| Field | Value |
|-------|-------|
| **Before** | `{{ before }}` |
| **After** | `{{ after }}` |
| **Files Changed** | {{ diff.files_changed }} |
| **Insertions** | +{{ diff.insertions }} |
| **Deletions** | -{{ diff.deletions }} |
| **Errors in Logs** | {{ logs.error_count }} |
| **Warnings in Logs** | {{ logs.warning_count }} |

---

## 📂 Changed Files

{% if diff.changed_files %}
{% for f in diff.changed_files[:20] %}
- `[{{ f.change_type }}]` {{ f.path }}
{% endfor %}
{% if diff.changed_files | length > 20 %}
- *(and {{ diff.changed_files | length - 20 }} more...)*
{% endif %}
{% else %}
*No changed files detected.*
{% endif %}

---

## 🔍 Log Analysis

- **Total lines scanned:** {{ logs.total_lines }}
- **Errors:** {{ logs.error_count }}
- **Warnings:** {{ logs.warning_count }}
- **Info:** {{ logs.info_count }}

{% if logs.top_errors %}
### Top Recurring Errors

{% for e in logs.top_errors %}
- **({{ e.count }}x)** `{{ e.message }}`
{% endfor %}
{% endif %}

{% if logs.notable_events %}
### ⚠️ Notable Events

{% for event in logs.notable_events %}
- {{ event }}
{% endfor %}
{% endif %}

{% if logs.sample_errors %}
### Sample Error Lines

```
{% for line in logs.sample_errors[:5] %}
{{ line }}
{% endfor %}
```
{% endif %}

---

## 🤖 AI Summary

{% if ai_summary %}
{{ ai_summary }}
{% else %}
> **Template mode** — No `GROQ_API_KEY` was provided.
>
> To get an AI-generated summary, sign up for a free Groq API key at [console.groq.com](https://console.groq.com) and set it as `GROQ_API_KEY` in your environment or GitHub Secrets.

### What Changed
{% if diff.changed_files %}
{% for f in diff.changed_files[:10] %}
- `{{ f.change_type | capitalize }}`: `{{ f.path }}`
{% endfor %}
{% else %}
- No file changes detected.
{% endif %}

### Issues Detected
{% if logs.error_count > 0 %}
- ⚠️ **{{ logs.error_count }} errors** found in logs. Manual review recommended.
{% for e in logs.top_errors[:3] %}
  - `{{ e.message }}` ({{ e.count }}x)
{% endfor %}
{% else %}
- ✅ No errors detected in logs.
{% endif %}

### Recommended Actions
1. Review the changed files listed above.
{% if logs.error_count > 0 %}
2. Investigate the {{ logs.error_count }} log errors before marking this deploy stable.
{% else %}
2. Monitor for 30 minutes post-deploy — logs look clean.
{% endif %}
3. Update this postmortem with any manual findings and link it to your issue tracker.
{% endif %}

---

## ✏️ Manual Notes

> *Add your own notes here after reviewing the deploy.*

- [ ] Confirmed deploy stable
- [ ] Alerts checked
- [ ] Team notified

---

*postmortem-pilot v{{ version }} | Apache 2.0 | https://github.com/eya-lachhab/postmortem-pilot*
"""


def render_report(
    output_path: str,
    diff_data: dict[str, Any],
    log_data: dict[str, Any],
    ai_summary: str | None,
    before: str,
    after: str,
) -> str:
    """Render postmortem markdown and write to output_path."""
    template = Template(TEMPLATE)
    content = template.render(
        timestamp=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
        before=before,
        after=after,
        diff=diff_data,
        logs=log_data,
        ai_summary=ai_summary,
        version=__version__,
    )

    out = Path(output_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(content, encoding="utf-8")
    return str(out)
